# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7f4306893c0b8721f695bfc64d11c06ddfd4e3faf145cab9c9d466838af1139d0402b55af2bd7b5a86cde5df94a834bb8e6c755950c26e5ce8e58ef83c87dae2

test:
  secret_key_base: ecad4238ed42d4061f8598905a3eaa18c0c8c79cf7bd01807cfdfd5c22847036d162053cb293a0cf21f1cb45b47122f426bdef6510a4109905d4ce9b586fcdf5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
